=== ashish1dev/AnnotationsTool/Images/CHIME-S/_Figure.schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Figure",
	"description": "A scientific figure ",
	"type": "object",

	"definitions": {
		"boundingbox": {
			"properties": {
				"width": {
					"type": "integer",
					"description": "Width of the boundingbox in pixel",
					"minimum": 0,
					"exclusiveMinimum": true
				},
				"height": {
					"type": "integer",
					"description": "Heigth of the boundingbox in pixel",
					"minimum": 0,
					"exclusiveMinimum": true
				},
				"center_x": {
					"type": "integer",
					"description": "X-coordinate of the center of the boundingbox in pixel"
				},
				"center_y": {
					"type": "integer",
					"description": "Y-coordinate of the center of the boundingbox in pixel"
				},
				"orientation": {
					"type": "number",
					"description": "Orientation of the boundingbox (rotation angle) around its center in degree."
				}
			},
			"required": ["width", "height", "center_x", "center_y"],
			"additionalProperties": false
		},

		"texxtelement": {
			"properties": {
				"boundingbox": {
					"$ref": "#/definitions/boundingbox"
				},
				"content": {
					"type": "string",
					"description": "Textual content of the element (inside the boundingbox)"
				}
			},
			"required": ["boundingbox", "content"]
		}
	},

	"properties": {
		"id": {
			"description": "The unique identifier for a figure",
			"type": "string"
		},
		"src": {
			"description": "The identifier of the source document",
			"type": "string"
		},
		"no.": {
			"description": "The extraction number of the figure",
			"type": "string"
		},
		"width": {
			"description": "The width of the figure",
			"type": "integer"
		},
		"height": {
			"description": "The height of the figure",
			"type": "integer"
		},
		"textelements": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/textelement"
			},
			"minItems": 1,
			"uniqueItems": true
		}
	},
	"required": ["id", "width", "height", "textelements"]
}

=== ashish1dev/AnnotationsTool/Images/CHIME-S/line028.json
{
	"id": "line028",
	"src": "CHIME-line",
	"no.": "028",
	"width": 453,
	"height": 293,
	"textelements": [ 
		{
			"content": "20",
			"boundingbox": {
				"center_x": 42,
				"center_y": 27,
				"width": 13,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "16",
			"boundingbox": {
				"center_x": 41,
				"center_y": 68,
				"width": 13,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "12",
			"boundingbox": {
				"center_x": 41,
				"center_y": 107,
				"width": 11,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "8",
			"boundingbox": {
				"center_x": 43,
				"center_y": 149,
				"width": 7,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "4",
			"boundingbox": {
				"center_x": 44,
				"center_y": 189,
				"width": 8,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "0",
			"boundingbox": {
				"center_x": 44,
				"center_y": 230,
				"width": 7,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "79",
			"boundingbox": {
				"center_x": 56,
				"center_y": 249,
				"width": 13,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "81",
			"boundingbox": {
				"center_x": 106,
				"center_y": 249,
				"width": 12,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "83",
			"boundingbox": {
				"center_x": 161,
				"center_y": 249,
				"width": 13,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "85",
			"boundingbox": {
				"center_x": 213,
				"center_y": 249,
				"width": 14,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "87",
			"boundingbox": {
				"center_x": 265,
				"center_y": 249,
				"width": 14,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "89",
			"boundingbox": {
				"center_x": 317,
				"center_y": 249,
				"width": 14,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "91",
			"boundingbox": {
				"center_x": 368,
				"center_y": 249,
				"width": 12,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "93",
			"boundingbox": {
				"center_x": 423,
				"center_y": 249,
				"width": 12,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "LBL % OF TOTAL LAB FUNDING",
			"boundingbox": {
				"center_x": 20,
				"center_y": 126,
				"width": 9,
				"height": 146,
				"orientation": 0
			}
		},
		{
			"content": "FISCAL YEAR",
			"boundingbox": {
				"center_x": 237,
				"center_y": 269,
				"width": 56,
				"height": 8,
				"orientation": 0
			}
		}
	]
}

=== ashish1dev/AnnotationsTool/Images/CHIME-S/pie046.json
{
	"id": "pie046",
	"src": "CHIME-pie",
	"no.": "046",
	"width": 420,
	"height": 257,
	"textelements": [ 
		{
			"content": "King County 11.2%",
			"boundingbox": {
				"center_x": 157,
				"center_y": 41,
				"width": 51,
				"height": 19,
				"orientation": 0
			}
		},
		{
			"content": "Kent School District 37.1%",
			"boundingbox": {
				"center_x": 55,
				"center_y": 147,
				"width": 80,
				"height": 18,
				"orientation": 0
			}
		},
		{
			"content": "State School Support 21.7%",
			"boundingbox": {
				"center_x": 225,
				"center_y": 238,
				"width": 86,
				"height": 19,
				"orientation": 0
			}
		},
		{
			"content": "Emergency Medical Services 1.9%",
			"boundingbox": {
				"center_x": 320,
				"center_y": 232,
				"width": 78,
				"height": 29,
				"orientation": 0
			}
		},
		{
			"content": "Hospital 0.7%",
			"boundingbox": {
				"center_x": 300,
				"center_y": 190,
				"width": 33,
				"height": 19,
				"orientation": 0
			}
		},
		{
			"content": "Rural Library District-G.O.Bond 0.3%",
			"boundingbox": {
				"center_x": 364,
				"center_y": 174,
				"width": 86,
				"height": 30,
				"orientation": 0
			}
		},
		{
			"content": "Rural Library District 3.9%",
			"boundingbox": {
				"center_x": 348,
				"center_y": 144,
				"width": 83,
				"height": 19,
				"orientation": 0
			}
		},
		{
			"content": "King County District #43 0.9%",
			"boundingbox": {
				"center_x": 383,
				"center_y": 109,
				"width": 51,
				"height": 28,
				"orientation": 0
			}
		},
		{
			"content": "King County Fire District #43 10.2%",
			"boundingbox": {
				"center_x": 320,
				"center_y": 83,
				"width": 68,
				"height": 30,
				"orientation": 0
			}
		},
		{
			"content": "Port of Seattle 2.0%",
			"boundingbox": {
				"center_x": 292,
				"center_y": 51,
				"width": 56,
				"height": 19,
				"orientation": 0
			}
		},
		{
			"content": "City of Covington 10.1%",
			"boundingbox": {
				"center_x": 238,
				"center_y": 25,
				"width": 70,
				"height": 19,
				"orientation": 0
			}
		}
	]
}

=== ashish1dev/AnnotationsTool/Images/CHIME-S/line059.json
{
	"id": "line059",
	"src": "CHIME-line",
	"no.": "059",
	"width": 550,
	"height": 360,
	"textelements": [ 
		{
			"content": "Micro$oft At Work",
			"boundingbox": {
				"center_x": 274,
				"center_y": 12,
				"width": 99,
				"height": 12,
				"orientation": 0
			}
		},
		{
			"content": "5,500",
			"boundingbox": {
				"center_x": 61,
				"center_y": 33,
				"width": 42,
				"height": 12,
				"orientation": 0
			}
		},
		{
			"content": "4,400",
			"boundingbox": {
				"center_x": 61,
				"center_y": 79,
				"width": 42,
				"height": 12,
				"orientation": 0
			}
		},
		{
			"content": "3,300",
			"boundingbox": {
				"center_x": 61,
				"center_y": 125,
				"width": 42,
				"height": 12,
				"orientation": 0
			}
		},
		{
			"content": "2,200",
			"boundingbox": {
				"center_x": 61,
				"center_y": 171,
				"width": 42,
				"height": 12,
				"orientation": 0
			}
		},
		{
			"content": "1,100",
			"boundingbox": {
				"center_x": 63,
				"center_y": 218,
				"width": 38,
				"height": 12,
				"orientation": 0
			}
		},
		{
			"content": "0",
			"boundingbox": {
				"center_x": 77,
				"center_y": 263,
				"width": 9,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "Problems",
			"boundingbox": {
				"center_x": 15,
				"center_y": 151,
				"width": 11,
				"height": 49,
				"orientation": 0
			}
		},
		{
			"content": "1998",
			"boundingbox": {
				"center_x": 121,
				"center_y": 279,
				"width": 36,
				"height": 13,
				"orientation": 0
			}
		},
		{
			"content": "1999",
			"boundingbox": {
				"center_x": 186,
				"center_y": 281,
				"width": 34,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "2000",
			"boundingbox": {
				"center_x": 250,
				"center_y": 280,
				"width": 39,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "2001",
			"boundingbox": {
				"center_x": 316,
				"center_y": 280,
				"width": 36,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "2002",
			"boundingbox": {
				"center_x": 381,
				"center_y": 280,
				"width": 38,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "2003",
			"boundingbox": {
				"center_x": 446,
				"center_y": 281,
				"width": 39,
				"height": 12,
				"orientation": 0
			}
		},
		{
			"content": "2004",
			"boundingbox": {
				"center_x": 511,
				"center_y": 281,
				"width": 39,
				"height": 12,
				"orientation": 0
			}
		},
		{
			"content": "Years",
			"boundingbox": {
				"center_x": 316,
				"center_y": 303,
				"width": 30,
				"height": 11,
				"orientation": 0
			}
		}
	]
}

=== ashish1dev/AnnotationsTool/Images/CHIME-S/pie038.json
{
	"id": "pie038",
	"src": "CHIME-pie",
	"no.": "038",
	"width": 439,
	"height": 391,
	"textelements": [ 
		{
			"content": "White",
			"boundingbox": {
				"center_x": 168,
				"center_y": 127,
				"width": 31,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "Hispanic",
			"boundingbox": {
				"center_x": 84,
				"center_y": 266,
				"width": 46,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "Filipilo",
			"boundingbox": {
				"center_x": 343,
				"center_y": 190,
				"width": 35,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "Black",
			"boundingbox": {
				"center_x": 304,
				"center_y": 152,
				"width": 29,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "Asian",
			"boundingbox": {
				"center_x": 232,
				"center_y": 117,
				"width": 31,
				"height": 9,
				"orientation": 0
			}
		}
	]
}

=== ashish1dev/AnnotationsTool/Images/CHIME-S/pie039.json
{
	"id": "pie039",
	"src": "CHIME-pie",
	"no.": "039",
	"width": 505,
	"height": 528,
	"textelements": [ 
		{
			"content": "Consumer Expenditures in 1992",
			"boundingbox": {
				"center_x": 259,
				"center_y": 46,
				"width": 453,
				"height": 27,
				"orientation": 0
			}
		},
		{
			"content": "Other 27%",
			"boundingbox": {
				"center_x": 122,
				"center_y": 181,
				"width": 38,
				"height": 27,
				"orientation": 0
			}
		},
		{
			"content": "Personal insurance and pensions 9%",
			"boundingbox": {
				"center_x": 87,
				"center_y": 308,
				"width": 130,
				"height": 32,
				"orientation": 0
			}
		},
		{
			"content": "Transportation 18%",
			"boundingbox": {
				"center_x": 253,
				"center_y": 398,
				"width": 134,
				"height": 15,
				"orientation": 0
			}
		},
		{
			"content": "Housing 32%",
			"boundingbox": {
				"center_x": 438,
				"center_y": 308,
				"width": 57,
				"height": 31,
				"orientation": 0
			}
		},
		{
			"content": "Food 14%",
			"boundingbox": {
				"center_x": 408,
				"center_y": 150,
				"width": 66,
				"height": 12,
				"orientation": 0
			}
		}
	]
}

=== ashish1dev/AnnotationsTool/Images/CHIME-S/line040.json
{
	"id": "line040",
	"src": "CHIME-line",
	"no.": "040",
	"width": 400,
	"height": 400,
	"textelements": [ 
		{
			"content": "500",
			"boundingbox": {
				"center_x": 47,
				"center_y": 47,
				"width": 18,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "400",
			"boundingbox": {
				"center_x": 47,
				"center_y": 105,
				"width": 18,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "300",
			"boundingbox": {
				"center_x": 47,
				"center_y": 163,
				"width": 18,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "200",
			"boundingbox": {
				"center_x": 47,
				"center_y": 220,
				"width": 18,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "100",
			"boundingbox": {
				"center_x": 47,
				"center_y": 278,
				"width": 17,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "0",
			"boundingbox": {
				"center_x": 53,
				"center_y": 335,
				"width": 6,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "1995",
			"boundingbox": {
				"center_x": 92,
				"center_y": 349,
				"width": 23,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "1996",
			"boundingbox": {
				"center_x": 150,
				"center_y": 349,
				"width": 23,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "1997",
			"boundingbox": {
				"center_x": 208,
				"center_y": 349,
				"width": 23,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "1998",
			"boundingbox": {
				"center_x": 265,
				"center_y": 349,
				"width": 23,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "1999",
			"boundingbox": {
				"center_x": 323,
				"center_y": 349,
				"width": 23,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "Years",
			"boundingbox": {
				"center_x": 209,
				"center_y": 371,
				"width": 40,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "Number of Cases",
			"boundingbox": {
				"center_x": 26,
				"center_y": 194,
				"width": 12,
				"height": 114,
				"orientation": 0
			}
		}
	]
}

=== ashish1dev/AnnotationsTool/Images/CHIME-S/pie048.json
{
	"id": "pie048",
	"src": "CHIME-pie",
	"no.": "048",
	"width": 392,
	"height": 306,
	"textelements": [ 
		{
			"content": "Counties 9%",
			"boundingbox": {
				"center_x": 95,
				"center_y": 28,
				"width": 48,
				"height": 27,
				"orientation": 0
			}
		},
		{
			"content": "Cities 48%",
			"boundingbox": {
				"center_x": 45,
				"center_y": 250,
				"width": 30,
				"height": 27,
				"orientation": 0
			}
		},
		{
			"content": "Bond Accounts 20%",
			"boundingbox": {
				"center_x": 320,
				"center_y": 229,
				"width": 53,
				"height": 44,
				"orientation": 0
			}
		},
		{
			"content": "Comm and Tech Colleges 2%",
			"boundingbox": {
				"center_x": 336,
				"center_y": 120,
				"width": 77,
				"height": 46,
				"orientation": 0
			}
		},
		{
			"content": "Special Districts 21%",
			"boundingbox": {
				"center_x": 257,
				"center_y": 30,
				"width": 45,
				"height": 44,
				"orientation": 0
			}
		}
	]
}

=== ashish1dev/AnnotationsTool/Images/CHIME-S/pie059.json
{
	"id": "pie059",
	"src": "CHIME-pie",
	"no.": "059",
	"width": 292,
	"height": 275,
	"textelements": [ 
		{
			"content": "Interest",
			"boundingbox": {
				"center_x": 247,
				"center_y": 57,
				"width": 52,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "Principle",
			"boundingbox": {
				"center_x": 32,
				"center_y": 200,
				"width": 52,
				"height": 13,
				"orientation": 0
			}
		}
	]
}
