=== ashish1dev/AnnotationsTool/Images/CHIME-S/_Figure.schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Figure",
	"description": "A scientific figure ",
	"type": "object",

	"definitions": {
		"boundingbox": {
			"properties": {
				"width": {
					"type": "integer",
					"description": "Width of the boundingbox in pixel",
					"minimum": 0,
					"exclusiveMinimum": true
				},
				"height": {
					"type": "integer",
					"description": "Heigth of the boundingbox in pixel",
					"minimum": 0,
					"exclusiveMinimum": true
				},
				"center_x": {
					"type": "integer",
					"description": "X-coordinate of the center of the boundingbox in pixel"
				},
				"center_y": {
					"type": "integer",
					"description": "Y-coordinate of the center of the boundingbox in pixel"
				},
				"orientation": {
					"type": "number",
					"description": "Orientation of the boundingbox (rotation angle) around its center in degree."
				}
			},
			"required": ["width", "height", "center_x", "center_y"],
			"additionalProperties": false
		},

		"texxtelement": {
			"properties": {
				"boundingbox": {
					"$ref": "#/definitions/boundingbox"
				},
				"content": {
					"type": "string",
					"description": "Textual content of the element (inside the boundingbox)"
				}
			},
			"required": ["boundingbox", "content"]
		}
	},

	"properties": {
		"id": {
			"description": "The unique identifier for a figure",
			"type": "string"
		},
		"src": {
			"description": "The identifier of the source document",
			"type": "string"
		},
		"no.": {
			"description": "The extraction number of the figure",
			"type": "string"
		},
		"width": {
			"description": "The width of the figure",
			"type": "integer"
		},
		"height": {
			"description": "The height of the figure",
			"type": "integer"
		},
		"textelements": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/textelement"
			},
			"minItems": 1,
			"uniqueItems": true
		}
	},
	"required": ["id", "width", "height", "textelements"]
}

=== ashish1dev/AnnotationsTool/Images/CHIME-S/line023.json
{
	"id": "line023",
	"src": "CHIME-line",
	"no.": "023",
	"width": 388,
	"height": 283,
	"textelements": [ 
		{
			"content": "Coolness factor of Nanosounds Websites",
			"boundingbox": {
				"center_x": 193,
				"center_y": 34,
				"width": 242,
				"height": 34,
				"orientation": 0
			}
		},
		{
			"content": "Number of Cheetos Consumed",
			"boundingbox": {
				"center_x": 33,
				"center_y": 151,
				"width": 28,
				"height": 118,
				"orientation": 0
			}
		},
		{
			"content": "Coolness",
			"boundingbox": {
				"center_x": 226,
				"center_y": 255,
				"width": 57,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "10",
			"boundingbox": {
				"center_x": 63,
				"center_y": 107,
				"width": 13,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "8",
			"boundingbox": {
				"center_x": 66,
				"center_y": 128,
				"width": 7,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "6",
			"boundingbox": {
				"center_x": 66,
				"center_y": 150,
				"width": 7,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "4",
			"boundingbox": {
				"center_x": 66,
				"center_y": 171,
				"width": 7,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "2",
			"boundingbox": {
				"center_x": 66,
				"center_y": 192,
				"width": 7,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "0",
			"boundingbox": {
				"center_x": 66,
				"center_y": 213,
				"width": 7,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "1",
			"boundingbox": {
				"center_x": 95,
				"center_y": 232,
				"width": 4,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "2",
			"boundingbox": {
				"center_x": 124,
				"center_y": 232,
				"width": 7,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "3",
			"boundingbox": {
				"center_x": 153,
				"center_y": 232,
				"width": 7,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "4",
			"boundingbox": {
				"center_x": 182,
				"center_y": 232,
				"width": 7,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "5",
			"boundingbox": {
				"center_x": 211,
				"center_y": 232,
				"width": 7,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "6",
			"boundingbox": {
				"center_x": 240,
				"center_y": 232,
				"width": 7,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "7",
			"boundingbox": {
				"center_x": 269,
				"center_y": 232,
				"width": 7,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "8",
			"boundingbox": {
				"center_x": 298,
				"center_y": 232,
				"width": 7,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "9",
			"boundingbox": {
				"center_x": 327,
				"center_y": 232,
				"width": 7,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "10",
			"boundingbox": {
				"center_x": 356,
				"center_y": 232,
				"width": 13,
				"height": 11,
				"orientation": 0
			}
		}
	]
}

=== ashish1dev/AnnotationsTool/Images/CHIME-S/line027.json
{
	"id": "line027",
	"src": "CHIME-line",
	"no.": "027",
	"width": 277,
	"height": 215,
	"textelements": [ 
		{
			"content": "$US dollars per barrel of Brent spot",
			"boundingbox": {
				"center_x": 103,
				"center_y": 9,
				"width": 200,
				"height": 12,
				"orientation": 0
			}
		},
		{
			"content": "35.0",
			"boundingbox": {
				"center_x": 17,
				"center_y": 32,
				"width": 24,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "30.0",
			"boundingbox": {
				"center_x": 17,
				"center_y": 53,
				"width": 24,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "25.0",
			"boundingbox": {
				"center_x": 17,
				"center_y": 74,
				"width": 24,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "20.0",
			"boundingbox": {
				"center_x": 17,
				"center_y": 97,
				"width": 24,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "15.0",
			"boundingbox": {
				"center_x": 17,
				"center_y": 118,
				"width": 23,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "10.0",
			"boundingbox": {
				"center_x": 17,
				"center_y": 140,
				"width": 23,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "05.0",
			"boundingbox": {
				"center_x": 17,
				"center_y": 162,
				"width": 24,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "0",
			"boundingbox": {
				"center_x": 26,
				"center_y": 184,
				"width": 6,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "1986",
			"boundingbox": {
				"center_x": 53,
				"center_y": 198,
				"width": 26,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "88",
			"boundingbox": {
				"center_x": 82,
				"center_y": 198,
				"width": 13,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "90",
			"boundingbox": {
				"center_x": 113,
				"center_y": 198,
				"width": 13,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "92",
			"boundingbox": {
				"center_x": 142,
				"center_y": 198,
				"width": 13,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "94",
			"boundingbox": {
				"center_x": 173,
				"center_y": 198,
				"width": 14,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "96",
			"boundingbox": {
				"center_x": 201,
				"center_y": 198,
				"width": 13,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "98",
			"boundingbox": {
				"center_x": 230,
				"center_y": 198,
				"width": 13,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "2000",
			"boundingbox": {
				"center_x": 260,
				"center_y": 198,
				"width": 27,
				"height": 8,
				"orientation": 0
			}
		}
	]
}

=== ashish1dev/AnnotationsTool/Images/CHIME-S/line030.json
{
	"id": "line030",
	"src": "CHIME-line",
	"no.": "030",
	"width": 190,
	"height": 204,
	"textelements": [ 
		{
			"content": "Rising",
			"boundingbox": {
				"center_x": 108,
				"center_y": 11,
				"width": 42,
				"height": 17,
				"orientation": 0
			}
		},
		{
			"content": "80",
			"boundingbox": {
				"center_x": 29,
				"center_y": 47,
				"width": 12,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "70",
			"boundingbox": {
				"center_x": 29,
				"center_y": 70,
				"width": 12,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "60",
			"boundingbox": {
				"center_x": 28,
				"center_y": 93,
				"width": 13,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "50",
			"boundingbox": {
				"center_x": 28,
				"center_y": 116,
				"width": 12,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "40",
			"boundingbox": {
				"center_x": 28,
				"center_y": 139,
				"width": 12,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "30",
			"boundingbox": {
				"center_x": 28,
				"center_y": 163,
				"width": 13,
				"height": 12,
				"orientation": 0
			}
		},
		{
			"content": "Percent",
			"boundingbox": {
				"center_x": 8,
				"center_y": 115,
				"width": 12,
				"height": 37,
				"orientation": 0
			}
		},
		{
			"content": "1988",
			"boundingbox": {
				"center_x": 60,
				"center_y": 195,
				"width": 21,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "1992",
			"boundingbox": {
				"center_x": 96,
				"center_y": 195,
				"width": 21,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "1996",
			"boundingbox": {
				"center_x": 132,
				"center_y": 195,
				"width": 21,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "2000",
			"boundingbox": {
				"center_x": 169,
				"center_y": 195,
				"width": 21,
				"height": 10,
				"orientation": 0
			}
		}
	]
}

=== ashish1dev/AnnotationsTool/Images/CHIME-S/line046.json
{
	"id": "line046",
	"src": "CHIME-line",
	"no.": "046",
	"width": 615,
	"height": 436,
	"textelements": [ 
		{
			"content": "30,000",
			"boundingbox": {
				"center_x": 62,
				"center_y": 24,
				"width": 34,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "28,000",
			"boundingbox": {
				"center_x": 62,
				"center_y": 54,
				"width": 34,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "26,000",
			"boundingbox": {
				"center_x": 62,
				"center_y": 84,
				"width": 34,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "24,000",
			"boundingbox": {
				"center_x": 62,
				"center_y": 114,
				"width": 34,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "22,000",
			"boundingbox": {
				"center_x": 62,
				"center_y": 144,
				"width": 34,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "20,000",
			"boundingbox": {
				"center_x": 62,
				"center_y": 174,
				"width": 34,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "18,000",
			"boundingbox": {
				"center_x": 62,
				"center_y": 204,
				"width": 33,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "16,000",
			"boundingbox": {
				"center_x": 62,
				"center_y": 234,
				"width": 33,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "14,000",
			"boundingbox": {
				"center_x": 62,
				"center_y": 264,
				"width": 33,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "12,000",
			"boundingbox": {
				"center_x": 62,
				"center_y": 294,
				"width": 33,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "10,000",
			"boundingbox": {
				"center_x": 62,
				"center_y": 324,
				"width": 33,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "Growth",
			"boundingbox": {
				"center_x": 25,
				"center_y": 173,
				"width": 10,
				"height": 42,
				"orientation": 0
			}
		},
		{
			"content": "1995",
			"boundingbox": {
				"center_x": 89,
				"center_y": 344,
				"width": 31,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "1996",
			"boundingbox": {
				"center_x": 137,
				"center_y": 344,
				"width": 31,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "1997",
			"boundingbox": {
				"center_x": 185,
				"center_y": 344,
				"width": 31,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "1998",
			"boundingbox": {
				"center_x": 233,
				"center_y": 344,
				"width": 31,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "1999",
			"boundingbox": {
				"center_x": 289,
				"center_y": 344,
				"width": 31,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "2000",
			"boundingbox": {
				"center_x": 346,
				"center_y": 344,
				"width": 32,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "2001",
			"boundingbox": {
				"center_x": 401,
				"center_y": 344,
				"width": 30,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "2002",
			"boundingbox": {
				"center_x": 449,
				"center_y": 344,
				"width": 31,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "2003",
			"boundingbox": {
				"center_x": 497,
				"center_y": 344,
				"width": 31,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "2004",
			"boundingbox": {
				"center_x": 546,
				"center_y": 344,
				"width": 32,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "2005",
			"boundingbox": {
				"center_x": 593,
				"center_y": 344,
				"width": 31,
				"height": 10,
				"orientation": 0
			}
		}
	]
}

=== ashish1dev/AnnotationsTool/Images/CHIME-S/line055.json
{
	"id": "line055",
	"src": "CHIME-line",
	"no.": "055",
	"width": 495,
	"height": 319,
	"textelements": [ 
		{
			"content": "10-Year Cycle Life Balance Chart - The highest is the Best",
			"boundingbox": {
				"center_x": 246,
				"center_y": 52,
				"width": 331,
				"height": 12,
				"orientation": 0
			}
		},
		{
			"content": "120",
			"boundingbox": {
				"center_x": 30,
				"center_y": 85,
				"width": 18,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "100",
			"boundingbox": {
				"center_x": 30,
				"center_y": 117,
				"width": 18,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "80",
			"boundingbox": {
				"center_x": 33,
				"center_y": 149,
				"width": 12,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "60",
			"boundingbox": {
				"center_x": 33,
				"center_y": 181,
				"width": 12,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "40",
			"boundingbox": {
				"center_x": 33,
				"center_y": 212,
				"width": 12,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "20",
			"boundingbox": {
				"center_x": 33,
				"center_y": 244,
				"width": 12,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "0",
			"boundingbox": {
				"center_x": 36,
				"center_y": 276,
				"width": 6,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "1956",
			"boundingbox": {
				"center_x": 66,
				"center_y": 289,
				"width": 24,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "1963",
			"boundingbox": {
				"center_x": 100,
				"center_y": 289,
				"width": 24,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "1973",
			"boundingbox": {
				"center_x": 134,
				"center_y": 289,
				"width": 24,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "1983",
			"boundingbox": {
				"center_x": 168,
				"center_y": 289,
				"width": 24,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "1993",
			"boundingbox": {
				"center_x": 201,
				"center_y": 289,
				"width": 24,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "2003",
			"boundingbox": {
				"center_x": 235,
				"center_y": 289,
				"width": 24,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "2013",
			"boundingbox": {
				"center_x": 269,
				"center_y": 289,
				"width": 24,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "2023",
			"boundingbox": {
				"center_x": 302,
				"center_y": 289,
				"width": 24,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "2033",
			"boundingbox": {
				"center_x": 336,
				"center_y": 289,
				"width": 24,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "2043",
			"boundingbox": {
				"center_x": 370,
				"center_y": 289,
				"width": 24,
				"height": 9,
				"orientation": 0
			}
		}
	]
}

=== ashish1dev/AnnotationsTool/Images/CHIME-S/line032.json
{
	"id": "line032",
	"src": "CHIME-line",
	"no.": "032",
	"width": 423,
	"height": 242,
	"textelements": [ 
		{
			"content": "Wt. In gm",
			"boundingbox": {
				"center_x": 24,
				"center_y": 88,
				"width": 13,
				"height": 54,
				"orientation": 0
			}
		},
		{
			"content": "80",
			"boundingbox": {
				"center_x": 53,
				"center_y": 16,
				"width": 16,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "0",
			"boundingbox": {
				"center_x": 56,
				"center_y": 187,
				"width": 7,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "1",
			"boundingbox": {
				"center_x": 74,
				"center_y": 207,
				"width": 3,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "2",
			"boundingbox": {
				"center_x": 92,
				"center_y": 207,
				"width": 6,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "3",
			"boundingbox": {
				"center_x": 109,
				"center_y": 207,
				"width": 6,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "4",
			"boundingbox": {
				"center_x": 126,
				"center_y": 207,
				"width": 7,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "5",
			"boundingbox": {
				"center_x": 143,
				"center_y": 207,
				"width": 5,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "6",
			"boundingbox": {
				"center_x": 160,
				"center_y": 207,
				"width": 6,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "7",
			"boundingbox": {
				"center_x": 177,
				"center_y": 207,
				"width": 6,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "8",
			"boundingbox": {
				"center_x": 194,
				"center_y": 207,
				"width": 6,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "9",
			"boundingbox": {
				"center_x": 211,
				"center_y": 207,
				"width": 6,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "10",
			"boundingbox": {
				"center_x": 228,
				"center_y": 207,
				"width": 11,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "11",
			"boundingbox": {
				"center_x": 244,
				"center_y": 207,
				"width": 9,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "12",
			"boundingbox": {
				"center_x": 262,
				"center_y": 207,
				"width": 11,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "13",
			"boundingbox": {
				"center_x": 279,
				"center_y": 207,
				"width": 11,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "14",
			"boundingbox": {
				"center_x": 297,
				"center_y": 207,
				"width": 12,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "15",
			"boundingbox": {
				"center_x": 313,
				"center_y": 207,
				"width": 11,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "16",
			"boundingbox": {
				"center_x": 329,
				"center_y": 207,
				"width": 11,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "17",
			"boundingbox": {
				"center_x": 346,
				"center_y": 207,
				"width": 11,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "18",
			"boundingbox": {
				"center_x": 364,
				"center_y": 207,
				"width": 11,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "19",
			"boundingbox": {
				"center_x": 381,
				"center_y": 207,
				"width": 11,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "20",
			"boundingbox": {
				"center_x": 398,
				"center_y": 207,
				"width": 12,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "SAMPLE NUMBER",
			"boundingbox": {
				"center_x": 204,
				"center_y": 226,
				"width": 123,
				"height": 11,
				"orientation": 0
			}
		}
	]
}

=== ashish1dev/AnnotationsTool/Images/CHIME-S/line060.json
{
	"id": "line060",
	"src": "CHIME-line",
	"no.": "060",
	"width": 612,
	"height": 396,
	"textelements": [ 
		{
			"content": "Marked Area Chart: Open",
			"boundingbox": {
				"center_x": 318,
				"center_y": 16,
				"width": 191,
				"height": 16,
				"orientation": 0
			}
		},
		{
			"content": "9.2",
			"boundingbox": {
				"center_x": 10,
				"center_y": 75,
				"width": 15,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "8.8",
			"boundingbox": {
				"center_x": 10,
				"center_y": 113,
				"width": 15,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "8.4",
			"boundingbox": {
				"center_x": 10,
				"center_y": 151,
				"width": 15,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "8",
			"boundingbox": {
				"center_x": 6,
				"center_y": 190,
				"width": 6,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "7.6",
			"boundingbox": {
				"center_x": 10,
				"center_y": 228,
				"width": 15,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "7.2",
			"boundingbox": {
				"center_x": 10,
				"center_y": 267,
				"width": 15,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "6.8",
			"boundingbox": {
				"center_x": 10,
				"center_y": 305,
				"width": 15,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "6.4",
			"boundingbox": {
				"center_x": 10,
				"center_y": 343,
				"width": 15,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "19970714",
			"boundingbox": {
				"center_x": 63,
				"center_y": 367,
				"width": 48,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "19970710",
			"boundingbox": {
				"center_x": 148,
				"center_y": 367,
				"width": 48,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "19970708",
			"boundingbox": {
				"center_x": 233,
				"center_y": 367,
				"width": 48,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "19970704",
			"boundingbox": {
				"center_x": 319,
				"center_y": 367,
				"width": 48,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "19970702",
			"boundingbox": {
				"center_x": 404,
				"center_y": 367,
				"width": 48,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "19970626",
			"boundingbox": {
				"center_x": 489,
				"center_y": 367,
				"width": 48,
				"height": 10,
				"orientation": 0
			}
		},
		{
			"content": "19970624",
			"boundingbox": {
				"center_x": 575,
				"center_y": 367,
				"width": 48,
				"height": 10,
				"orientation": 0
			}
		}
	]
}

=== ashish1dev/AnnotationsTool/Images/CHIME-S/pie044.json
{
	"id": "pie044",
	"src": "CHIME-pie",
	"no.": "044",
	"width": 420,
	"height": 279,
	"textelements": [ 
		{
			"content": "King County 11.4%",
			"boundingbox": {
				"center_x": 165,
				"center_y": 16,
				"width": 52,
				"height": 20,
				"orientation": 0
			}
		},
		{
			"content": "Kent School District 37.4%",
			"boundingbox": {
				"center_x": 45,
				"center_y": 135,
				"width": 83,
				"height": 20,
				"orientation": 0
			}
		},
		{
			"content": "State School Support 21.9%",
			"boundingbox": {
				"center_x": 228,
				"center_y": 244,
				"width": 89,
				"height": 19,
				"orientation": 0
			}
		},
		{
			"content": "Library District 5.8%",
			"boundingbox": {
				"center_x": 330,
				"center_y": 166,
				"width": 62,
				"height": 20,
				"orientation": 0
			}
		},
		{
			"content": "King County Fire District #37 10.3%",
			"boundingbox": {
				"center_x": 331,
				"center_y": 109,
				"width": 71,
				"height": 32,
				"orientation": 0
			}
		},
		{
			"content": "Port of Seattle 2.0%",
			"boundingbox": {
				"center_x": 303,
				"center_y": 60,
				"width": 58,
				"height": 20,
				"orientation": 0
			}
		},
		{
			"content": "City of Covington 10.2%",
			"boundingbox": {
				"center_x": 274,
				"center_y": 29,
				"width": 72,
				"height": 20,
				"orientation": 0
			}
		}
	]
}
