=== ashish1dev/AnnotationsTool/Images/CHIME-S/_Figure.schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Figure",
	"description": "A scientific figure ",
	"type": "object",

	"definitions": {
		"boundingbox": {
			"properties": {
				"width": {
					"type": "integer",
					"description": "Width of the boundingbox in pixel",
					"minimum": 0,
					"exclusiveMinimum": true
				},
				"height": {
					"type": "integer",
					"description": "Heigth of the boundingbox in pixel",
					"minimum": 0,
					"exclusiveMinimum": true
				},
				"center_x": {
					"type": "integer",
					"description": "X-coordinate of the center of the boundingbox in pixel"
				},
				"center_y": {
					"type": "integer",
					"description": "Y-coordinate of the center of the boundingbox in pixel"
				},
				"orientation": {
					"type": "number",
					"description": "Orientation of the boundingbox (rotation angle) around its center in degree."
				}
			},
			"required": ["width", "height", "center_x", "center_y"],
			"additionalProperties": false
		},

		"texxtelement": {
			"properties": {
				"boundingbox": {
					"$ref": "#/definitions/boundingbox"
				},
				"content": {
					"type": "string",
					"description": "Textual content of the element (inside the boundingbox)"
				}
			},
			"required": ["boundingbox", "content"]
		}
	},

	"properties": {
		"id": {
			"description": "The unique identifier for a figure",
			"type": "string"
		},
		"src": {
			"description": "The identifier of the source document",
			"type": "string"
		},
		"no.": {
			"description": "The extraction number of the figure",
			"type": "string"
		},
		"width": {
			"description": "The width of the figure",
			"type": "integer"
		},
		"height": {
			"description": "The height of the figure",
			"type": "integer"
		},
		"textelements": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/textelement"
			},
			"minItems": 1,
			"uniqueItems": true
		}
	},
	"required": ["id", "width", "height", "textelements"]
}

=== ashish1dev/AnnotationsTool/Images/CHIME-S/pie061.json
{
	"id": "pie061",
	"src": "CHIME-pie",
	"no.": "061",
	"width": 400,
	"height": 300,
	"textelements": [ 
		{
			"content": "Pie Chart Example",
			"boundingbox": {
				"center_x": 49,
				"center_y": 7,
				"width": 97,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "Item 1 17",
			"boundingbox": {
				"center_x": 284,
				"center_y": 208,
				"width": 26,
				"height": 22,
				"orientation": 0
			}
		},
		{
			"content": "Item 2 28",
			"boundingbox": {
				"center_x": 84,
				"center_y": 62,
				"width": 28,
				"height": 22,
				"orientation": 0
			}
		},
		{
			"content": "Item 3 5",
			"boundingbox": {
				"center_x": 126,
				"center_y": 265,
				"width": 28,
				"height": 22,
				"orientation": 0
			}
		}
	]
}

=== ashish1dev/AnnotationsTool/Images/CHIME-S/line022.json
{
	"id": "line022",
	"src": "CHIME-line",
	"no.": "022",
	"width": 442,
	"height": 282,
	"textelements": [ 
		{
			"content": "Neutropenia Model (Control)",
			"boundingbox": {
				"center_x": 221,
				"center_y": 23,
				"width": 192,
				"height": 13,
				"orientation": 0
			}
		},
		{
			"content": "2.5",
			"boundingbox": {
				"center_x": 44,
				"center_y": 60,
				"width": 15,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "2",
			"boundingbox": {
				"center_x": 49,
				"center_y": 92,
				"width": 5,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "1.5",
			"boundingbox": {
				"center_x": 45,
				"center_y": 123,
				"width": 14,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "1",
			"boundingbox": {
				"center_x": 49,
				"center_y": 156,
				"width": 2,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "0.5",
			"boundingbox": {
				"center_x": 44,
				"center_y": 187,
				"width": 15,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "0",
			"boundingbox": {
				"center_x": 49,
				"center_y": 219,
				"width": 5,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "Absolute Neutrophils",
			"boundingbox": {
				"center_x": 24,
				"center_y": 140,
				"width": 11,
				"height": 117,
				"orientation": 0
			}
		},
		{
			"content": "1",
			"boundingbox": {
				"center_x": 75,
				"center_y": 236,
				"width": 2,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "2",
			"boundingbox": {
				"center_x": 101,
				"center_y": 236,
				"width": 5,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "3",
			"boundingbox": {
				"center_x": 127,
				"center_y": 236,
				"width": 5,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "4",
			"boundingbox": {
				"center_x": 153,
				"center_y": 236,
				"width": 5,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "5",
			"boundingbox": {
				"center_x": 180,
				"center_y": 236,
				"width": 6,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "6",
			"boundingbox": {
				"center_x": 206,
				"center_y": 236,
				"width": 5,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "7",
			"boundingbox": {
				"center_x": 232,
				"center_y": 236,
				"width": 5,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "8",
			"boundingbox": {
				"center_x": 258,
				"center_y": 236,
				"width": 5,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "9",
			"boundingbox": {
				"center_x": 284,
				"center_y": 236,
				"width": 5,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "10",
			"boundingbox": {
				"center_x": 310,
				"center_y": 236,
				"width": 11,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "11",
			"boundingbox": {
				"center_x": 335,
				"center_y": 236,
				"width": 9,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "12",
			"boundingbox": {
				"center_x": 363,
				"center_y": 236,
				"width": 10,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "13",
			"boundingbox": {
				"center_x": 389,
				"center_y": 236,
				"width": 10,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "14",
			"boundingbox": {
				"center_x": 415,
				"center_y": 236,
				"width": 10,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "Day after treatment",
			"boundingbox": {
				"center_x": 245,
				"center_y": 258,
				"width": 114,
				"height": 12,
				"orientation": 0
			}
		}
	]
}

=== ashish1dev/AnnotationsTool/Images/CHIME-S/pie032.json
{
	"id": "pie032",
	"src": "CHIME-pie",
	"no.": "032",
	"width": 375,
	"height": 231,
	"textelements": [ 
		{
			"content": "Big Sky Families 13%",
			"boundingbox": {
				"center_x": 199,
				"center_y": 9,
				"width": 141,
				"height": 15,
				"orientation": 0
			}
		},
		{
			"content": "Fast-Track Families 13%",
			"boundingbox": {
				"center_x": 279,
				"center_y": 62,
				"width": 157,
				"height": 14,
				"orientation": 0
			}
		},
		{
			"content": "Upper Crust 13%",
			"boundingbox": {
				"center_x": 274,
				"center_y": 109,
				"width": 112,
				"height": 15,
				"orientation": 0
			}
		},
		{
			"content": "Big Fish, Small Pond 5%",
			"boundingbox": {
				"center_x": 294,
				"center_y": 138,
				"width": 157,
				"height": 16,
				"orientation": 0
			}
		},
		{
			"content": "Country Casual 3%",
			"boundingbox": {
				"center_x": 278,
				"center_y": 161,
				"width": 133,
				"height": 16,
				"orientation": 0
			}
		},
		{
			"content": "Second City Elite 2%",
			"boundingbox": {
				"center_x": 271,
				"center_y": 180,
				"width": 136,
				"height": 15,
				"orientation": 0
			}
		},
		{
			"content": "Other 66%",
			"boundingbox": {
				"center_x": 235,
				"center_y": 204,
				"width": 73,
				"height": 12,
				"orientation": 0
			}
		}
	]
}

=== ashish1dev/AnnotationsTool/Images/CHIME-S/line037.json
{
	"id": "line037",
	"src": "CHIME-line",
	"no.": "037",
	"width": 297,
	"height": 164,
	"textelements": [ 
		{
			"content": "100",
			"boundingbox": {
				"center_x": 8,
				"center_y": 13,
				"width": 14,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "80",
			"boundingbox": {
				"center_x": 9,
				"center_y": 40,
				"width": 10,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "60",
			"boundingbox": {
				"center_x": 9,
				"center_y": 68,
				"width": 10,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "40",
			"boundingbox": {
				"center_x": 9,
				"center_y": 95,
				"width": 10,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "20",
			"boundingbox": {
				"center_x": 9,
				"center_y": 123,
				"width": 10,
				"height": 8,
				"orientation": 0
			}
		},
		{
			"content": "0",
			"boundingbox": {
				"center_x": 11,
				"center_y": 150,
				"width": 5,
				"height": 8,
				"orientation": 0
			}
		}
	]
}

=== ashish1dev/AnnotationsTool/Images/CHIME-S/dbar002.json
{
	"id": "dbar002",
	"src": "CHIME-dbar",
	"no.": "002",
	"width": 383,
	"height": 325,
	"textelements": [ 
		{
			"content": "Use of Library Services FY 1998/99",
			"boundingbox": {
				"center_x": 191,
				"center_y": 21,
				"width": 213,
				"height": 12,
				"orientation": 0
			}
		},
		{
			"content": "20,000",
			"boundingbox": {
				"center_x": 28,
				"center_y": 59,
				"width": 31,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "10,000",
			"boundingbox": {
				"center_x": 28,
				"center_y": 159,
				"width": 31,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "0",
			"boundingbox": {
				"center_x": 42,
				"center_y": 258,
				"width": 4,
				"height": 7,
				"orientation": 0
			}
		},
		{
			"content": "circulation",
			"boundingbox": {
				"center_x": 84,
				"center_y": 274,
				"width": 46,
				"height": 7,
				"orientation": 0
			}
		},
		{
			"content": "reserves",
			"boundingbox": {
				"center_x": 147,
				"center_y": 275,
				"width": 42,
				"height": 5,
				"orientation": 0
			}
		},
		{
			"content": "interlibrary loan",
			"boundingbox": {
				"center_x": 210,
				"center_y": 282,
				"width": 49,
				"height": 22,
				"orientation": 0
			}
		},
		{
			"content": "reference (closed stacks)",
			"boundingbox": {
				"center_x": 273,
				"center_y": 290,
				"width": 46,
				"height": 39,
				"orientation": 0
			}
		},
		{
			"content": "freshmen",
			"boundingbox": {
				"center_x": 352,
				"center_y": 145,
				"width": 44,
				"height": 7,
				"orientation": 0
			}
		},
		{
			"content": "seniors",
			"boundingbox": {
				"center_x": 347,
				"center_y": 164,
				"width": 34,
				"height": 7,
				"orientation": 0
			}
		}
	]
}

=== ashish1dev/AnnotationsTool/Images/CHIME-S/dbar003.json
{
	"id": "dbar003",
	"src": "CHIME-dbar",
	"no.": "003",
	"width": 509,
	"height": 238,
	"textelements": [ 
		{
			"content": "Histogram(vertical bar chart)",
			"boundingbox": {
				"center_x": 235,
				"center_y": 16,
				"width": 172,
				"height": 14,
				"orientation": 0
			}
		},
		{
			"content": "30",
			"boundingbox": {
				"center_x": 17,
				"center_y": 46,
				"width": 13,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "25",
			"boundingbox": {
				"center_x": 17,
				"center_y": 72,
				"width": 13,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "20",
			"boundingbox": {
				"center_x": 17,
				"center_y": 72,
				"width": 13,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "20",
			"boundingbox": {
				"center_x": 17,
				"center_y": 99,
				"width": 13,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "15",
			"boundingbox": {
				"center_x": 18,
				"center_y": 125,
				"width": 12,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "10",
			"boundingbox": {
				"center_x": 18,
				"center_y": 151,
				"width": 12,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "5",
			"boundingbox": {
				"center_x": 21,
				"center_y": 178,
				"width": 6,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "0",
			"boundingbox": {
				"center_x": 21,
				"center_y": 204,
				"width": 6,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "Whortleberry",
			"boundingbox": {
				"center_x": 68,
				"center_y": 219,
				"width": 63,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "Sheperd's",
			"boundingbox": {
				"center_x": 149,
				"center_y": 219,
				"width": 53,
				"height": 11,
				"orientation": 0
			}
		},
		{
			"content": "Blackbird",
			"boundingbox": {
				"center_x": 224,
				"center_y": 218,
				"width": 41,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "Humble",
			"boundingbox": {
				"center_x": 305,
				"center_y": 218,
				"width": 34,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "American",
			"boundingbox": {
				"center_x": 382,
				"center_y": 218,
				"width": 45,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "Apple",
			"boundingbox": {
				"center_x": 461,
				"center_y": 219,
				"width": 27,
				"height": 11,
				"orientation": 0
			}
		}
	]
}

=== ashish1dev/AnnotationsTool/Images/CHIME-S/line020.json
{
	"id": "line020",
	"src": "CHIME-line",
	"no.": "020",
	"width": 434,
	"height": 311,
	"textelements": [ 
		{
			"content": "Library Gate Counts - 1998",
			"boundingbox": {
				"center_x": 195,
				"center_y": 23,
				"width": 165,
				"height": 14,
				"orientation": 0
			}
		},
		{
			"content": "18000",
			"boundingbox": {
				"center_x": 31,
				"center_y": 59,
				"width": 30,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "16000",
			"boundingbox": {
				"center_x": 31,
				"center_y": 77,
				"width": 30,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "14000",
			"boundingbox": {
				"center_x": 31,
				"center_y": 96,
				"width": 30,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "12000",
			"boundingbox": {
				"center_x": 31,
				"center_y": 114,
				"width": 30,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "10000",
			"boundingbox": {
				"center_x": 31,
				"center_y": 133,
				"width": 30,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "8000",
			"boundingbox": {
				"center_x": 34,
				"center_y": 151,
				"width": 24,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "6000",
			"boundingbox": {
				"center_x": 34,
				"center_y": 170,
				"width": 24,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "4000",
			"boundingbox": {
				"center_x": 34,
				"center_y": 188,
				"width": 24,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "2000",
			"boundingbox": {
				"center_x": 34,
				"center_y": 207,
				"width": 24,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "0",
			"boundingbox": {
				"center_x": 43,
				"center_y": 225,
				"width": 6,
				"height": 9,
				"orientation": 0
			}
		},
		{
			"content": "January",
			"boundingbox": {
				"center_x": 54,
				"center_y": 253,
				"width": 11,
				"height": 39,
				"orientation": 0
			}
		},
		{
			"content": "Februrary",
			"boundingbox": {
				"center_x": 83,
				"center_y": 256,
				"width": 11,
				"height": 44,
				"orientation": 0
			}
		},
		{
			"content": "March",
			"boundingbox": {
				"center_x": 112,
				"center_y": 249,
				"width": 9,
				"height": 30,
				"orientation": 0
			}
		},
		{
			"content": "April",
			"boundingbox": {
				"center_x": 142,
				"center_y": 245,
				"width": 11,
				"height": 22,
				"orientation": 0
			}
		},
		{
			"content": "May",
			"boundingbox": {
				"center_x": 171,
				"center_y": 244,
				"width": 11,
				"height": 20,
				"orientation": 0
			}
		},
		{
			"content": "June",
			"boundingbox": {
				"center_x": 200,
				"center_y": 245,
				"width": 9,
				"height": 23,
				"orientation": 0
			}
		},
		{
			"content": "July",
			"boundingbox": {
				"center_x": 230,
				"center_y": 243,
				"width": 11,
				"height": 19,
				"orientation": 0
			}
		},
		{
			"content": "August",
			"boundingbox": {
				"center_x": 260,
				"center_y": 251,
				"width": 11,
				"height": 35,
				"orientation": 0
			}
		},
		{
			"content": "September",
			"boundingbox": {
				"center_x": 289,
				"center_y": 260,
				"width": 11,
				"height": 52,
				"orientation": 0
			}
		},
		{
			"content": "October",
			"boundingbox": {
				"center_x": 317,
				"center_y": 253,
				"width": 9,
				"height": 39,
				"orientation": 0
			}
		},
		{
			"content": "November",
			"boundingbox": {
				"center_x": 347,
				"center_y": 258,
				"width": 9,
				"height": 49,
				"orientation": 0
			}
		},
		{
			"content": "December",
			"boundingbox": {
				"center_x": 376,
				"center_y": 258,
				"width": 9,
				"height": 49,
				"orientation": 0
			}
		}
	]
}

=== ashish1dev/AnnotationsTool/Images/CHIME-S/pie047.json
{
	"id": "pie047",
	"src": "CHIME-pie",
	"no.": "047",
	"width": 375,
	"height": 305,
	"textelements": [ 
		{
			"content": "Goods 14.62%",
			"boundingbox": {
				"center_x": 117,
				"center_y": 98,
				"width": 38,
				"height": 25,
				"orientation": 0
			}
		},
		{
			"content": "Intergovernmental 5.30%",
			"boundingbox": {
				"center_x": 60,
				"center_y": 153,
				"width": 94,
				"height": 26,
				"orientation": 0
			}
		},
		{
			"content": "Permits 23.38%",
			"boundingbox": {
				"center_x": 91,
				"center_y": 246,
				"width": 39,
				"height": 24,
				"orientation": 0
			}
		},
		{
			"content": "Taxes 54.11%",
			"boundingbox": {
				"center_x": 324,
				"center_y": 197,
				"width": 39,
				"height": 24,
				"orientation": 0
			}
		},
		{
			"content": "Miscellaneous 0.81%",
			"boundingbox": {
				"center_x": 245,
				"center_y": 69,
				"width": 73,
				"height": 24,
				"orientation": 0
			}
		},
		{
			"content": "Forfeitures 1.78%",
			"boundingbox": {
				"center_x": 164,
				"center_y": 66,
				"width": 56,
				"height": 24,
				"orientation": 0
			}
		}
	]
}
